filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

filebeat.modules:
  - module: zeek
# DNS is disabled due to mismatched timestamp
#    connection:
#      enabled: true
#    dns:
#      enabled: true
#      var.paths:
#        - /pcap/dns*.log
    http:
      enabled: true
      var.paths:
        - /pcap/http*.log
    files:
      enabled: true
      var.paths:
        - /pcap/files*.log
    ssl:
      enabled: true
      var.paths:
        - /pcap/ssl*.log
    notice:
      enabled: true
      var.paths:
        - /pcap/notice*.log

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: '${KIBANA_HOST:kibana:5601}'

setup.dashboards.enabled: true
